name: big-bear-obsidian-livesync
services:
  app:
    container_name: obsidian-livesync
    environment:
      - COUCHDB_PASSWORD=casaos
      - COUCHDB_USER=casaos
    image: couchdb:3.3.3
    labels:
      icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/obsidian.png?raw=true
    ports:
      - mode: ingress
        target: 5984
        published: "5984"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-obsidian-livesync/data/couchdb
        target: /opt/couchdb/data
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/big-bear-obsidian-livesync/data/local.ini
        target: /opt/couchdb/etc/local.ini
        bind:
          create_host_path: true
    x-casaos:
      ports:
        - container: "5984"
          description:
            en_us: "Container Port: 5984"
      volumes:
        - container: /opt/couchdb/data
          description:
            en_us: "Container Path: /opt/couchdb/data"
        - container: /opt/couchdb/etc/local.ini
          description:
            en_us: "Container Path: /opt/couchdb/etc/local.ini"
    devices: []
    cap_add: []
    command: []
    networks:
      - default
    privileged: false
    hostname: obsidian-livesync
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 3577M
networks:
  default:
    name: big-bear-obsidian-livesync_default
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: Self-hosted database for synchronizing Obsidian vaults.
  developer: ""
  icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/obsidian.png?raw=true
  main: app
  port_map: "5984"
  store_app_id: big-bear-obsidian-livesync
  tagline:
    en_us: Self-hosted database for synchronizing Obsidian vaults.
  thumbnail: ""
  tips:
    before_install:
      en_us: >
        Run this script before installing the big-bear-obsidian-livesync
        application:


        ```

        bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-obsidian-livesync-local-ini/run.sh)"

        ```


        After running this script, you need to restart the container.
  title:
    en_us: Obsidian Livesync
    custom: ""
  hostname: ""
  scheme: http
  index: /
